### ISSUE TITLE
Building the Xrange apps without any IDEs

### ISSUE THREAD

**Issue by kqorany** [NetBlocks/XRange#1]
Hi Folks,

I am looking for building the apps without any IDEs just using the GCC ARM toolchain. So, I would like to ask if there is anybody did that before. If yes, please share with me how you did it.

Thanks in advance,
Khaled

**Comment by NetBlocks** [comment]
Hi Khaled,
In LoRaMac version 3.4.1 it is possible to build the firmware under Linux with make please read the description from link https://github.com/NetBlocks/XRange/tree/master/LoRaMac/make/XRange
Regards,
Netblocks
